#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Install parameters are automatically saved as settings
#
# Settings are automatically loaded as bash variables
# in every app script context, therefore typically these will exist:
# - $domain
# - $path
# - $language
# ... etc
#
# Resources defined in the manifest are provisioned prior to this script
# and corresponding settings are also available, such as:
# - $install_dir
# - $port
# - $db_name
# ...

#
# $app is the app id (i.e. 'example' for first install, 
# or 'example__2', '__3', ... for multi-instance installs)
#

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app ..." --weight=1

### `ynh_add_fpm_config` is used to set up a PHP config.
### You can remove it if your app doesn't use PHP.
### `ynh_add_fpm_config` will use the files conf/php-fpm.conf
### If you're not using these lines:
###		- You can remove these files in conf/.
###		- Remove the section "BACKUP THE PHP-FPM CONFIGURATION" in the backup script
###		- Remove also the section "REMOVE PHP-FPM CONFIGURATION" in the remove script
###		- As well as the section "RESTORE THE PHP-FPM CONFIGURATION" in the restore script
###		  with the reload at the end of the script.
###		- And the section "PHP-FPM CONFIGURATION" in the upgrade script

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

cat /etc/nginx/conf.d/$domain.d/$app.conf

#=================================================
# TEMP DIRECTORY CREATION
#=================================================
# remplacé par directive subdir dans le manifest.toml
# code précédent:
# 	webdav_temp_dir=$install_dir_temp
# 	mkdir -p "$webdav_temp_dir"
# 	chown -R www-data:www-data "$webdav_temp_dir"

#=================================================
# USERS' DIRECTORY CREATION
#=================================================
# le répertoire de chaque utilisateur sera déormais /home/yunohost.multimedia/$user qui existe par défaut
# il faudra juste créer un index.html dans chqcun de ss répertoire, pour affichage depuis les tuiles sur un navigateur

users_list=$(ynh_user_list)
for u in $users_list
	do
		create_user $u
	done
 
#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
