#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_nginx

#=================================================
# USERS' DIRECTORY CREATION
#=================================================
# le répertoire de chaque utilisateur sera désormais /home/yunohost.multimedia/$user qui existe par défaut
# néanmoins, lors du test par package_checker, ce répertoire semble ne pas être systématiquement présent.
# il faut donc le créer s'il n'existe pas
if [[ !(-d "$chemin_utilisateurs") ]]
  then
   ynh_multimedia_build_main_dir
fi

# puis on ajoute www-data au groupe multimedia pour donner accès en http (protocole webdav)
# si multimedia n'existe pas, yunohost le créera
ynh_multimedia_addaccess www-data

# attention, sur ma version, les répertoires sous /home/yunohost.multimedia ne sont pas dans le groupe "multimedia".
#  Il faut rectifier car le protocole webdav utilise le groupe www-data pour écrire en protocole http dans les répertoires
chgrp -f -R multimedia $chemin_utilisateurs

# il faudra juste créer un index.html dans chacun de ss répertoire, pour affichage depuis les tuiles sur un navigateur
users_list=$(ynh_user_list)
for u in $users_list
	do
		create_user $u
	done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
