#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_nginx

#=================================================
# REMOVE DATAs
#=================================================

users_list=$(ynh_user_list)
for u in $users_list
	do
		remove_user $u
	done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
