#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Settings are automatically loaded as bash variables
# in every app script context, therefore typically these will exist:
# - $domain
# - $path
# - $language
# - $install_dir
# - $port
# ...

# For remove operations :
# - the core will deprovision every resource defined in the manifest **after** this script is ran
# this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================

ynh_script_progression --message="Removing system configurations related to $app..." --weight=1


ynh_remove_nginx_config

ynh_secure_remove $data_dir
#=================================================
# REMOVE DATAs 
#=================================================
users_list=$(ynh_user_list)
for u in $users_list
	do
		rm -f $chemin_données/$u/index.html 
	done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
